import {
  LIKE_COMMENT_USER_STATUS_ENUM,
  SORT_DIRECTION_ENUM,
} from './interfaces'

const MIN_COMMENT_LENGTH = 20
const MAX_COMMENT_LENGTH = 300

const DEFAULTS = {
  SORT_BY: 'createdAt',
  PAGE_NUMBER: 1,
  PAGE_SIZE: 10,
  SORT_DIRECTION: SORT_DIRECTION_ENUM,
}

const DEFAULTS_COMMENT_LIKE_STATUS = {
  LIKES_COUNT: 0,
  DISLIKES_COUNT: 0,
  MY_STATUS: LIKE_COMMENT_USER_STATUS_ENUM.None,
}

export {
  MIN_COMMENT_LENGTH,
  MAX_COMMENT_LENGTH,
  DEFAULTS,
  DEFAULTS_COMMENT_LIKE_STATUS,
}
