import { LIKE_POST_USER_STATUS_ENUM, SORT_DIRECTION_ENUM } from './interfaces'

const MIN_LENGTH = 1
const MAX_POST_TITLE_LENGTH = 30
const MAX_POST_SHORT_DESCRIPTION_LENGTH = 100
const MAX_POST_CONTENT_LENGTH = 1000

const DEFAULTS = {
  SORT_BY: 'createdAt',
  PAGE_NUMBER: 1,
  PAGE_SIZE: 10,
  SORT_DIRECTION: SORT_DIRECTION_ENUM,
}

const DEFAULTS_LIKE_STATUS = {
  LIKES_COUNT: 0,
  DISLIKES_COUNT: 0,
  MAX_NEWEST_LIKES_COUNT: 3,
  MY_STATUS: LIKE_POST_USER_STATUS_ENUM.None,
}

export {
  MIN_LENGTH,
  MAX_POST_TITLE_LENGTH,
  MAX_POST_SHORT_DESCRIPTION_LENGTH,
  MAX_POST_CONTENT_LENGTH,
  DEFAULTS,
  DEFAULTS_LIKE_STATUS,
}
