const DEFAULTS = {
  EMAIL_CONFIRMATION_EXPIRES: 10,
  PASSWORD_RECOVERY_CONFIRMATION_EXPIRES: 30,
  SALT_ROUNDS: 10,
}

const MIN_PASSWORD_LENGTH = 6
const MAX_PASSWORD_LENGTH = 20

const MIN_LOGIN_LENGTH = 3
const MAX_LOGIN_LENGTH = 10

const REFRESH_TOKEN_COOKIE_NAME = 'refreshToken'

export {
  DEFAULTS,
  REFRESH_TOKEN_COOKIE_NAME,
  MIN_PASSWORD_LENGTH,
  MAX_PASSWORD_LENGTH,
  MIN_LOGIN_LENGTH,
  MAX_LOGIN_LENGTH,
}
